network:
  name: corporate_network
  hosts: 
    - name: host1
      ip: 192.168.1.10
    - name: host2
      ip: 192.168.1.20
  subnets:
    - subnet_name: office
      range: 192.168.1.0/24
